programs=Pergunta01 Pergunta02 Pergunta03 Pergunta04 Pergunta05  Pergunta06 Pergunta07
all:$(programs)

Pergunta01:Pergunta01.cpp
	g++ -o Pergunta01 Pergunta01.cpp

Pergunta02:Pergunta02.cpp
	g++ -o Pergunta02 Pergunta02.cpp

Pergunta03:Pergunta03.cpp
	g++ -o Pergunta03 Pergunta03.cpp

Pergunta04:Pergunta04.cpp
	g++ -o Pergunta04 Pergunta04.cpp

Pergunta05:Pergunta05.cpp
	g++ -o Pergunta05 Pergunta05.cpp

Pergunta06:Pergunta06.cpp
	g++ -o Pergunta06 Pergunta06.cpp

Pergunta07:Pergunta07.cpp
	g++ -o Pergunta07 Pergunta07.cpp


clean:
	rm $(programs)
