all:initCondFromFile initCondFromFileFunction

initCondFromFile:initCondFromFile.cpp
	g++ initCondFromFile.cpp -o initCondFromFile

initCondFromFileFunction:initCondFromFileFunction.cpp
	g++ initCondFromFileFunction.cpp -o initCondFromFileFunction




