all:example exampleGetopt myGetopt

example:example.cpp
	g++ -lgsl -lgslcblas -lm example.cpp -o example

myGetopt:myGetopt.cpp
	g++ -o myGetopt myGetopt.cpp

exampleGetopt:exampleGetopt.cpp
	g++ -o exampleGetopt exampleGetopt.cpp


