
all:rw2D_Trials rw2D_oneTrial

rw2D_NNN_Trials:rw2D_NNN_Trials.cpp
	g++ -o rw2D_NNN_Trials rw2D_NNN_Trials.cpp

rw2D_Trials:rw2D_Trials.cpp
	g++ -o rw2D_Trials rw2D_Trials.cpp

rw2D:rw2D.cpp
	g++ -o rw2D rw2D.cpp

rw2D_oneTrial:rw2D_oneTrial.cpp
	g++ -o rw2D_oneTrial rw2D_oneTrial.cpp

rw2Dtrials:rw2Dtrials.cpp
	g++ -o rw2Dtrials rw2Dtrials.cpp

clean:
	rm  rw2D_Trials 
