all:array3Das1D_a array3Das1D array2D LimitArray LimitArrayHeap LimitArrayHeap2D

array3Das1D_a:array3Das1D_a.cpp
	g++ -o array3Das1D_a array3Das1D_a.cpp

array3Das1D:array3Das1D.cpp
	g++ -o array3Das1D array3Das1D.cpp

array2D:array2D.cpp
	g++ -o array2D array2D.cpp

LimitArray:LimitArray.cpp
	g++ -o LimitArray LimitArray.cpp 

LimitArrayHeap:LimitArrayHeap.cpp
	g++ -o LimitArrayHeap LimitArrayHeap.cpp 

LimitArrayHeap2D:LimitArrayHeap2D.cpp
	g++ -o LimitArrayHeap2D LimitArrayHeap2D.cpp 
