all:integers initArray globalArray Const if xor

xor:xor.cpp
	$(CXX) -o xor xor.cpp

if:if.cpp
	$(CXX) -o if if.cpp

integers:integers.cpp
	$(CXX) -o integers integers.cpp

initArray:initArray.cpp
	$(CXX) -o initArray initArray.cpp

globalArray:globalArray.cpp
	$(CXX) -o globalArray globalArray.cpp -lm

Const:Const.cpp
	$(CXX) -o Const Const.cpp -lm

#for.cpp
#if.cpp
#integers.cpp
#Macros.cpp
#net.cpp
