all: exercise001A exercise002A exercise003 serialExercise003


exercise001A:exercise001A.c
	gcc -fopenmp -o exercise001A exercise001A.c

exercise002A:exercise002A.c
	gcc -fopenmp -o exercise002A exercise002A.c

exercise003:exercise003.c
	gcc -fopenmp -o exercise003 exercise003.c

serialExercise003:exercise003.c
	gcc -o serialExercise003 exercise003.c

