all:filenameFormats returnString stringsize

filenameFormats:filenameFormats.cpp
	g++ -o filenameFormats filenameFormats.cpp

stringsize:stringsize.cpp
	g++ -o stringsize stringsize.cpp

returnString:returnString.cpp
	g++ -o returnString returnString.cpp
